### ISSUE TITLE
Difference between SocketHandlerThread and SocketHandlerRunner

### ISSUE THREAD

**Issue by lincolnneu** [gortonator/bsds-6650#5]
https://github.com/gortonator/bsds-6650/blob/10c2050ed8c622eb00603d437944bdab78599007/code/week-3/solutions/SocketHandlerRunnable.java#L46

SocketHandlerThread does not close socket but SocketHandlerRunnable does. Is this the only difference?

**Comment by gortonator** [comment]
line 45 SocketHandlerThread?

**Comment by lincolnneu** [comment]
Did not notice there is another SocketHandlerThread in the solution. I was comparing to https://github.com/gortonator/bsds-6650/blob/master/code/week-3/SocketHandlerThread.java

It seems that the difference of SocketHandlerThread and SocketHandlerRunnable is the first one extends Thread while the second one implements Runnable. They are equivalent , right?

**Comment by gortonator** [comment]
yup
